main:
  model_name: OWL_L14
  bf16: True
  datasets: all
  ds_seed: ???
  testing: ???
  save_model: ???
  use_first_set_only: True
  sweep_name: best_hps
  override_epochs: null
  retrieval_each_batch: True
  chkpt_path: null
  optim: AdamW
  weight_decay: 0.0
  setting: seq_full_shot
  test_only: False
  proxy_test_only: False
  ft_upper_bound: False
  prompt_type: "imagenet"
  early_stopping: False
  early_stopping_thresh: -0.02
  early_stopping_patience: 5
  wandb_proj: null
  max_buffer_size: 40000
  retrieval_seed: null
  sampling_seed: null
  wandb_mode: online
  test_batch: 36
  train_batch: 16
  x_dims: [3,840,840]
  y_dims: [16]
  retrieval_strat: null
  k_shots: null 
  n_ways: null
  zero_shot_only: False
  coreset_name: O365_VG
  coreset_rotation: 1
  reset_dedup_on: "dataset"
  dedup_prop: null
  using_v100: False
  n_replays: 1
  DER_alpha: 2.0
  DER_beta: 1.0
  o365_thresh: 0.15
  VG_thresh: 0.0
  coreset_N: 50
  base_coreset: False
  cls_specific: False
  sub_exp: 0.45
  wandb_id: 1000
  ubal_SV: False
  ubal_SV_coeff: null
  ub_coeff: 0.7
  swil_cls_coeff: 1.0
  swil_reduce_type: min
  cls_embeds: True
  bal_prob_type: null
  n_tok: 8
  eval_batch: null
  loss_adaptive: False
  replay_thresh: null
  proxy_each_dataset: False
  swil_ada_ent: null
  swil_ada: none
  swil_ds_config: null
  save_ds_models: False
